# Generated by Django 5.1.5 on 2025-01-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created_datetime",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="post",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
